import React from "react";
import {
  Home, BookOpen, Book, MessageCircle, Calendar, Grid2X2, Shield, ArrowLeft,
  Mail, Lock, AlertCircle, User, Hash, Phone, Check, X, Plus, Pencil, Edit2,
  Trash2, Eye, EyeOff, HelpCircle, Cpu, Award, Video, Users, TrendingUp, Star,
  Compass, Zap, FileText, CheckCircle, Clock, CheckSquare, Sun, Activity,
  Smartphone, Info, LogOut, RefreshCw, Send, ArrowRight, Heart, ChevronRight,
  ChevronDown, ChevronUp, UserCheck, UserPlus, Bell, Monitor, AlertTriangle,
  Layers, Download, Briefcase, Unlock, Search, Filter, Settings, Globe,
  ChevronLeft, Camera, Image, Link, Copy, Share2, MoreHorizontal, MoreVertical,
  Menu, Minus, Maximize, Minimize, RotateCw, Upload, Paperclip, Mic,
  Volume2, VolumeX, Play, Pause, SkipBack, SkipForward, Repeat, Shuffle,
  Bookmark, Tag, Flag, Archive, Inbox, Folder, File, Code, Terminal, Database,
  Wifi, Battery, Power, MapPin, Navigation, BarChart, PieChart, TrendingDown,
  DollarSign, CreditCard, ShoppingCart, Package, Truck, Wrench, Key,
  Lightbulb, Target, List, AlignLeft, AlignCenter, Bold, Italic, Underline,
  Type, LayoutGrid, LayoutList, Grid, Columns,
} from "lucide-react";

const ICON_MAP = {
  "home": Home,
  "book-open": BookOpen,
  "book": Book,
  "message-circle": MessageCircle,
  "calendar": Calendar,
  "grid": LayoutGrid,
  "shield": Shield,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "mail": Mail,
  "lock": Lock,
  "alert-circle": AlertCircle,
  "alert-triangle": AlertTriangle,
  "user": User,
  "users": Users,
  "user-check": UserCheck,
  "user-plus": UserPlus,
  "hash": Hash,
  "phone": Phone,
  "check": Check,
  "check-circle": CheckCircle,
  "check-square": CheckSquare,
  "x": X,
  "plus": Plus,
  "minus": Minus,
  "edit-2": Edit2,
  "edit": Pencil,
  "trash-2": Trash2,
  "eye": Eye,
  "eye-off": EyeOff,
  "help-circle": HelpCircle,
  "cpu": Cpu,
  "award": Award,
  "video": Video,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "star": Star,
  "compass": Compass,
  "zap": Zap,
  "file-text": FileText,
  "clock": Clock,
  "sun": Sun,
  "activity": Activity,
  "smartphone": Smartphone,
  "info": Info,
  "log-out": LogOut,
  "refresh-cw": RefreshCw,
  "send": Send,
  "heart": Heart,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "bell": Bell,
  "monitor": Monitor,
  "layers": Layers,
  "download": Download,
  "upload": Upload,
  "briefcase": Briefcase,
  "unlock": Unlock,
  "search": Search,
  "filter": Filter,
  "settings": Settings,
  "globe": Globe,
  "camera": Camera,
  "image": Image,
  "link": Link,
  "copy": Copy,
  "share-2": Share2,
  "share": Share2,
  "more-horizontal": MoreHorizontal,
  "more-vertical": MoreVertical,
  "menu": Menu,
  "bookmark": Bookmark,
  "tag": Tag,
  "flag": Flag,
  "archive": Archive,
  "inbox": Inbox,
  "folder": Folder,
  "file": File,
  "code": Code,
  "terminal": Terminal,
  "database": Database,
  "wifi": Wifi,
  "battery": Battery,
  "power": Power,
  "map-pin": MapPin,
  "navigation": Navigation,
  "bar-chart": BarChart,
  "pie-chart": PieChart,
  "dollar-sign": DollarSign,
  "credit-card": CreditCard,
  "shopping-cart": ShoppingCart,
  "package": Package,
  "truck": Truck,
  "tool": Wrench,
  "key": Key,
  "target": Target,
  "list": List,
  "type": Type,
  "mic": Mic,
  "volume-2": Volume2,
  "volume-x": VolumeX,
  "play": Play,
  "pause": Pause,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  "repeat": Repeat,
  "columns": Columns,
  "lightbulb": Lightbulb,
};

export function Feather({ name, size = 24, color = "currentColor", style }) {
  const Icon = ICON_MAP[name] || HelpCircle;
  return <Icon size={size} color={color} style={style} />;
}

export const AntDesign = Feather;
export const MaterialIcons = Feather;
export const Ionicons = Feather;
export const FontAwesome = Feather;
export const MaterialCommunityIcons = Feather;
