const colors = {
  light: {
    text: "#0D1B2A",
    tint: "#1565C0",
    background: "#F0F4FF",
    foreground: "#0D1B2A",
    card: "#FFFFFF",
    cardForeground: "#0D1B2A",
    primary: "#1565C0",
    primaryForeground: "#FFFFFF",
    secondary: "#E8EDF7",
    secondaryForeground: "#1E3A5F",
    muted: "#EEF2FF",
    mutedForeground: "#6B7FA3",
    accent: "#00897B",
    accentForeground: "#FFFFFF",
    highlight: "#FF8F00",
    highlightForeground: "#FFFFFF",
    destructive: "#C62828",
    destructiveForeground: "#FFFFFF",
    border: "#D0D9F0",
    input: "#D0D9F0",
    success: "#2E7D32",
    successForeground: "#FFFFFF",
    warning: "#E65100",
    warningForeground: "#FFFFFF",
  },
  dark: {
    text: "#E8EEFF",
    tint: "#5B8DEF",
    background: "#0A0F1E",
    foreground: "#E8EEFF",
    card: "#131B2E",
    cardForeground: "#E8EEFF",
    primary: "#5B8DEF",
    primaryForeground: "#FFFFFF",
    secondary: "#1A2540",
    secondaryForeground: "#C5D0F0",
    muted: "#1A2540",
    mutedForeground: "#7B90C0",
    accent: "#26A69A",
    accentForeground: "#FFFFFF",
    highlight: "#FFA726",
    highlightForeground: "#0D1B2A",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#1E3054",
    input: "#1E3054",
    success: "#4CAF50",
    successForeground: "#FFFFFF",
    warning: "#FF9800",
    warningForeground: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
